language: python

cache: pip

dist: xenial

python:
  - "3.6"
  - "3.7"

jobs:
  include:
    # Test optional dependencies.
    - python: "3.7"
      install: pip install .[dev]
      script: pytest

install: pip install -r requirements.txt

script:
  - pytest

before_deploy:
  # PyPI deploy fails if there are unstaged changes
  # Reset any unstaged changes (such as updates to Pipfile or Pipfile.lock)
  - git checkout -- .

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    python: "3.7"
