language: python

cache: pip

dist: xenial

python:
  - "3.6"
  - "3.7"

jobs:
  include:
    # Test optional dependencies.
    - python: "3.7"
      install: pip install .[dev]
      script: pytest

install: pip install -r requirements.txt

script:
  - pytest

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  skip_existing: true
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
